name: Python package

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.12
    - name: Install dependencies
      run: |
        poetry install
    - name: Type check with mypy
      run: |
        poetry run mypy .
